#!/usr/bin/groovy

pipeline {
  agent {
    dockerfile {
      filename 'Dockerfile'
      reuseNode true
    }
  }
  options {
    timestamps()
    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_vagabundo_build']])
    disableConcurrentBuilds()
  }
  environment {
    HOME = '.'
    CI = 'true'
    AWS_ARTEFACTS = 's3://BUCKET_ID'
    AWS_DEFAULT_REGION = 'eu-central-1'
  }

  stages {
    stage('Install') {
      steps {
        sh 'npm install'
        sh 'npm rebuild node-sass --force'
      }
    }
    stage('Build') {
      steps {
        sh 'npm run build'
        sh 'npm run build:staging'
      }
    }
    stage('Test') {
      steps {
        sh 'npm run test:prod'
        sh 'npm run lint'
        sh 'npm run e2e'
      }
    }
    stage('Upload') {
      when {
        branch 'master'
      }
      steps {
        sh 'aws s3 cp dist/vagabundo-frontend/ ${AWS_ARTEFACTS}/vagabundo-frontend/production/${BUILD_NUMBER} --recursive'
        sh 'aws s3 cp dist-staging/vagabundo-frontend/ ${AWS_ARTEFACTS}/vagabundo-frontend/staging/${BUILD_NUMBER} --recursive'
      }
    }
  }

  post {
    always {
      deleteDir()
    }
  }
}
