name: deploy vagabundo backend to staging
on:
  push:
    paths:
      - "vagabundo-backend-node/**"

jobs:         
  test_deploy_backend:
    name: test and deploy backend
    strategy: 
     matrix:
      node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Directory
        working-directory: ./vagabundo-backend-node
        run: sam deploy --stack-name vagabundo-staging-backend --s3-bucket vagabundo-staging-backend --capabilities CAPABILITY_IAM --region eu-central-1

