#test comment
name: deploy vagabundo-frontend to staging
on: 
  push:
    paths: 
      - 'vagabundo-frontend/**'

env:
  BUCKET_NAME : "<example-bucket-name>"
  AWS_REGION : "<example-aws-region>"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test_frontend:
    name: build and deploy frontend
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dep
        run: |
         cd vagabundo-frontend
         npm install
         
      - name: Build
        run: |
         cd vagabundo-frontend
         npm run build --if-present
        
      - name: Test
        run: |
         cd vagabundo-frontend
         npm run test
         npm run lint
         npm run e2e

  S3PackageUpload:
   runs-on: ubuntu-latest
   steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::385321346563:role/OIDC_S3-Deployment
        role-session-name: s3-depl
        aws-region: eu-central-1
      # Upload a file to AWS s3
      - name:  deploy to s3
        run: aws s3 sync ./dist/vagabundo-frontend s3://vagabundo.staging.frontend
      
