name: Deploy Staging

on: push

jobs:
  staging-deploy:
    name: Deploy Vagabundo to staging
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "::set-output name=environment::$ENVIRONMENT"

      - name: Prepare Network
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: vagabundo-staging-network
          template: vagabundo-backend-node/templates/network.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "Env=staging"

      - name: Deploy Database
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: vagabundo-staging-database
          template: vagabundo-backend-node/templates/database.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "Env=staging,NetworkStack=vagabundo-staging-network"

      - name: sam build
        uses: TractorZoom/sam-cli-action@v.0.2.0
        with:
          sam_command: "build"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: sam deploy
        uses: TractorZoom/sam-cli-action@v.0.2.0
        with:
          sam_command: "deploy"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
